const data = [
  {
    userID: "123",
    displayName: "Alloha",
    gameplayed: 856,
    wins: 666,
    winrate: 66.5,
    picture: "../../public/images/default.png",
    elo: 157000,
  },
  {
    userID: "123",
    displayName: "Bine",
    gameplayed: 856,
    wins: 666,
    winrate: 66.5,
    picture: "../../public/images/default.png",
    elo: 157000,
  },
  {
    userID: "123",
    displayName: "Zak",
    gameplayed: 856,
    wins: 666,
    winrate: 66.5,
    picture: "../../public/images/default.png",
    elo: 157000,
  },
  {
    userID: "123",
    displayName: "Cjam",
    gameplayed: 856,
    wins: 666,
    winrate: 66.5,
    picture: "../../public/images/default.png",
    elo: 157000,
  },
  {
    userID: "123",
    displayName: "Wassin",
    gameplayed: 856,
    wins: 666,
    winrate: 66.5,
    picture: "../../public/images/default.png",
    elo: 157000,
  },
  {
    userID: "123",
    displayName: "Bine",
    gameplayed: 856,
    wins: 666,
    winrate: 66.5,
    picture: "../../public/images/default.png",
    elo: 157000,
  },
];

export default data;
